In [1]:
import cv2

In [2]:
jeff=cv2.imread('jeff.jpg')

In [3]:
bill=cv2.imread('bill.jpg')

In [4]:
model=cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

In [5]:
face=model.detectMultiScale(jeff)

In [6]:
face2=model.detectMultiScale(bill)
face,face2

(array([[149, 144, 296, 296]], dtype=int32),
 array([[161, 144, 277, 277]], dtype=int32))

In [7]:
jeff_face=jeff[149:149+296,144:144+296]
bill_face=bill[162:162+287,134:134+287]

In [8]:
jeff_crop=cv2.resize(jeff_face,(287,287),)
bill_crop=cv2.resize(bill_face,(296,296),)

In [9]:
jeff_crop,bill_crop


(array([[[230, 234, 245],
         [230, 232, 243],
         [230, 232, 243],
         ...,
         [230, 234, 245],
         [228, 232, 243],
         [229, 233, 244]],
 
        [[230, 233, 247],
         [231, 233, 244],
         [230, 232, 243],
         ...,
         [229, 232, 246],
         [230, 233, 247],
         [231, 233, 244]],
 
        [[230, 233, 247],
         [228, 232, 243],
         [230, 232, 243],
         ...,
         [230, 233, 247],
         [228, 231, 245],
         [229, 233, 244]],
 
        ...,
 
        [[229, 231, 242],
         [230, 232, 242],
         [230, 232, 242],
         ...,
         [120,  84,  76],
         [130,  95,  90],
         [130,  98,  92]],
 
        [[228, 230, 240],
         [229, 231, 241],
         [229, 230, 240],
         ...,
         [133, 114, 106],
         [139, 119, 112],
         [130, 108, 102]],
 
        [[228, 230, 240],
         [229, 230, 240],
         [230, 231, 241],
         ...,
         [181, 168, 166],
  

In [10]:
jeff[149:149+296,144:144+296]=bill_crop
bill[162:162+287,134:134+287 ]=jeff_crop

In [11]:
import numpy

In [12]:
img=numpy.concatenate((jeff,bill),axis=1)

In [13]:
cv2.imshow("h",img)
cv2.waitKey()
cv2.destroyAllWindows()